### ISSUE TITLE
Web server Integration issue

### ISSUE THREAD

**Issue by rakeshkasinathan** [WING-NUS/Neural-ParsCit#23]
***While using the below command i am getting issue
root@13d0d88a6545:/usr/src# gunicorn -b 0.0.0.0:8000 -w 1 --timeout 60 run_app:app
[2019-03-29 10:45:33 +0000] [34] [INFO] Starting gunicorn 19.9.0
[2019-03-29 10:45:33 +0000] [34] [INFO] Listening at: http://0.0.0.0:8000 (34)
[2019-03-29 10:45:33 +0000] [34] [INFO] Using worker: sync
[2019-03-29 10:45:33 +0000] [38] [INFO] Booting worker with pid: 38
[INFO] 2019-03-29 10:45:49,179: Loading model from /usr/src/models/neuralParscit and using word embeddings from /usr/src/vectors_with_unk.kv
[2019-03-29 10:45:49 +0000] [38] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/run_app.py", line 8, in <module>
    app = create_app(CONFIG)
  File "/usr/src/app/__init__.py", line 26, in create_app
    model, inference = get_model(model_path, word_emb_path)
  File "/usr/src/app/utils.py", line 7, in get_model
    g.model = Model(model_path=model_path)
  File "/usr/src/model.py", line 55, in __init__
    with open(self.parameters_path, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/usr/src/models/neuralParscit/parameters.pkl'
[2019-03-29 10:45:49 +0000] [38] [INFO] Worker exiting (pid: 38)
[2019-03-29 10:45:49 +0000] [34] [INFO] Shutting down: Master
[2019-03-29 10:45:49 +0000] [34] [INFO] Reason: Worker failed to boot.

**Comment by kylase** [comment]
I have no issue running the webserver. You need to check your `models` directory.

Do you have a new model? If you have you need to set `MODEL_PATH` environment variable to specify the new path for the model, otherwise it will use `models/neuralParscit/`.

**Comment by rakeshkasinathan** [comment]
My models directory are available but still i am getting the above issue,

**Comment by kylase** [comment]
You will to describe your issue more precisely.

Please refer to this [link](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines) and describe your issue. Thanks.
